// packages/vue/reference-app/routes/Error.vue
<script lang="ts">
import type { LoaderFunction } from "@remix-run/router";
import { json, useLoaderData } from "remix-router-vue";

export const loader: LoaderFunction = async ({ request }) => {
  let isLoaderError =
    new URL(request.url).searchParams.get("type") === "loader";
  if (isLoaderError) {
    throw new Error("Loader error!");
  }
  return json({});
};
</script>

<script setup lang="ts">
const data = useLoaderData();
</script>

<template>
  <h2>Render Error: {{ data.foo.bar }}</h2>
  ;
</template>

// packages/preact/reference-app/routes/Error.tsx
import type { LoaderFunction } from "@remix-run/router";
import { json, useLoaderData } from "remix-router-preact";

export const loader: LoaderFunction = async ({ request }) => {
  let isLoaderError =
    new URL(request.url).searchParams.get("type") === "loader";
  if (isLoaderError) {
    throw new Error("Loader error!");
  }
  return json({});
};

export default function ErrorComponent() {
  let data = useLoaderData() as ReturnType<typeof loader>;
  return <h2>Render Error: {data.foo.bar}</h2>;
}
