// packages/svelte/reference-app/components/TaskItem.svelte
<script lang="ts">
  import { Link, useFetcher } from "remix-router-svelte";

  export let task;

  let fetcher = useFetcher();
  let isDeleting = fetcher.formData != null;
</script>

<span>{task.task}</span>
&nbsp;
<Link to="/tasks/{task.id}">Open</Link>
&nbsp;
<svelte:component
  this={fetcher.Form}
  style="display: inline"
  action="/tasks"
  method="post"
>
  <button type="submit" name="taskId" value={task.id} disabled={isDeleting}>
    {isDeleting ? "Deleting..." : "❌"}
  </button>
</svelte:component>

// packages/react-stub/reference-app/components/TaskItem.tsx
import { Link, useFetcher,  } from "react-router-dom";

import type { Task } from "../tasks";

export interface TaskItemProps {
  task: Task;
}

export default function TaskItem({ task }: TaskItemProps) {
  let fetcher = useFetcher();
  let isDeleting = fetcher.formData != null; 

  return (
    <>
      <span>{task.task}</span> <Link to={`/tasks/${task.id}`}>Open</Link>{" "}
      <fetcher.Form style={{ display: "inline" }} action="/tasks" method="post">
        <button
          type="submit"
          name="taskId"
          value={task.id}
          disabled={isDeleting}
        >
          {isDeleting ? "Deleting..." : "❌"}
        </button>
      </fetcher.Form>
    </>
  );
}
