// packages/svelte/reference-app/routes/Nested/Parent.svelte
<script lang="ts" context="module">
  import { json, type LoaderFunction } from "@remix-run/router";
  import { sleep } from "~/utils";
  interface LoaderData {
    data: string;
  }

  export const loader: LoaderFunction = async () => {
    await sleep();
    return json<LoaderData>({ data: "parent loader data" });
  };
</script>

<script lang="ts">
  import { Outlet, useLoaderData } from "remix-router-svelte";
  let data = useLoaderData();
</script>

<h2>Parent Layout</h2>
<p id="parent">
  Parent data: {data.data}
</p>
<Outlet />

// packages/react-stub/reference-app/routes/nested/Parent.tsx
import { LoaderFunction } from "@remix-run/router";
import { json, Outlet, useLoaderData } from "react-router-dom";
import { sleep } from "~/utils";

interface LoaderData {
  data: string;
}

export const loader: LoaderFunction = async () => {
  await sleep();
  return json<LoaderData>({ data: "parent loader data" });
};

export default function Parent() {
  const data = useLoaderData() as LoaderData;

  return (
    <>
      <h2>Parent Layout</h2>
      <p id="parent">Parent data: {data.data}</p>
      <Outlet />
    </>
  );
}
