// packages/vue/reference-app/routes/Defer.vue
<script>
import { Await, defer, useLoaderData } from "remix-router-vue";

const resolve = (d, ms) => new Promise((r) => setTimeout(() => r(d), ms));

const reject = (d, ms) => new Promise((_, r) => setTimeout(() => r(d), ms));

export async function loader() {
  return defer({
    critical: await resolve("Critical Data", 1000),
    lazy: resolve("Lazy Data ✅", 1000),
    lazyError: reject("Lazy Error 💥", 2000),
  });
}
</script>

<script setup>
const data = useLoaderData();
</script>

<template>
  <p id="critical-data">Critical Data: {{ data.critical }}</p>

  <Suspense>
    <template #fallback>
      <p id="lazy-value-fallback">Loading data...</p>
    </template>
    <Await :resolve="data.lazy" v-slot="value">
      <p id="lazy-value">Value: {{ value }}</p>
    </Await>
  </Suspense>

  <Suspense>
    <template #fallback>
      <p id="lazy-error-fallback">Loading error...</p>
    </template>
    <Await :resolve="data.lazyError">
      <template #default="value">
        <p>Value: {{ value }}</p>
      </template>
      <template #error="error">
        <p id="lazy-error">Error: {{ error }}</p>
      </template>
    </Await>
  </Suspense>
</template>

// packages/react-stub/reference-app/routes/Defer.tsx
import * as React from "react";
import { Await, defer, useAsyncError, useLoaderData } from "react-router-dom";

const resolve = (d: string, ms: number): Promise<string> =>
  new Promise((r) => setTimeout(() => r(d), ms));

const reject = (d: string, ms: number) =>
  new Promise((_, r) => setTimeout(() => r(d), ms));

interface LoaderData {
  critical: string;
  lazy: Promise<String>;
  lazyError: Promise<string>;
}

export async function loader() {
  return defer({
    critical: await resolve("Critical Data", 500),
    lazy: resolve("Lazy Data ✅", 1000),
    lazyError: reject("Lazy Error 💥", 1500),
  });
}

function ErrorElement() {
  let error = useAsyncError();
  return <p>{`Error! ${error}`}</p>;
}

export default function Defer() {
  let data = useLoaderData() as LoaderData;

  return (
    <>
      <p>Critical Data: {data.critical}</p>

      <React.Suspense fallback={<p>Loading lazy data...</p>}>
        <Await resolve={data.lazy}>
          {(value) => <p>Lazy Data: {value}</p>}
        </Await>
      </React.Suspense>

      <React.Suspense fallback={<p>Loading lazy error...</p>}>
        <Await resolve={data.lazyError} errorElement={<ErrorElement />}>
          {() => <p>Nope!</p>}
        </Await>
      </React.Suspense>
    </>
  );
}
