// packages/svelte/reference-app/routes/Root.svelte
<script>
  import {
    Outlet,
    Link,
    useNavigate,
    useLocation,
    useNavigation,
    useNavigationType,
    useMatches,
  } from "remix-router-svelte";

  const links = {
    Index: "/",
    Parent: "/parent",
    Child: "/parent/child",
    Redirect: "/redirect?location=%2Fparent%2Fchild",
    // "Loader Error": "/error?type=loader",
    // "Render Error": "/error?type=render",
    // "Nested Loader Error": "/parent/error?type=loader",
    // "Nested Render Error": "/parent/error?type=render",
    Tasks: "/tasks",
    "Add Task": "/tasks/new",
  };

  let navigation = useNavigation();
  let matches = useMatches();
  let navigationType = useNavigationType();
  let location = useLocation();
  $: hooks = {
    navigationType: JSON.stringify($navigationType),
    location: JSON.stringify($location),
    navigation: JSON.stringify($navigation),
    matches: JSON.stringify($matches),
  };

  let navigate = useNavigate();
</script>

<h1>Root Layout</h1>
<nav>
  {#each Object.entries(links) as [text, href]}
    <Link to={href}>{text}</Link>
  {/each}
  <button id="back" on:click={() => navigate(-1)}>Go Back</button>
</nav>
{#each Object.entries(hooks) as [k, v] (k)}
  <p>
    {k}():
  </p>
  <pre id={k}>{v}</pre>
{/each}
<Outlet />

// packages/react-stub/reference-app/routes/Root.tsx
import {
  Link,
  Outlet,
  useLocation,
  useMatches,
  useNavigate,
  useNavigation,
  useNavigationType,
} from "react-router-dom";

export default function Root() {
  let links = {
    Index: "/",
    Parent: "/parent",
    Child: "/parent/child",
    Redirect: "/redirect?location=%2Fparent%2Fchild",
    "Loader Error": "/error?type=loader",
    "Render Error": "/error?type=render",
    "Nested Loader Error": "/parent/error?type=loader",
    "Nested Render Error": "/parent/error?type=render",
    Tasks: "/tasks",
    "Add Task": "/tasks/new",
  };
  let hooks = {
    navigationType: JSON.stringify(useNavigationType()),
    location: JSON.stringify(useLocation()),
    navigation: JSON.stringify(useNavigation()),
    matches: JSON.stringify(useMatches()),
  };
  let navigate = useNavigate();

  return (
    <>
      <h1>Root Layout</h1>
      <nav>
        {Object.entries(links).map(([text, href]) => (
          <Link key={href} to={href}>
            {text}
          </Link>
        ))}
        <button id="back" onClick={() => navigate(-1)}>
          Go Back
        </button>
      </nav>
      {Object.entries(hooks).map(([k, v]) => (
        <p>
          {k}():
          <pre id={k}>{v}</pre>
        </p>
      ))}
      <Outlet />
    </>
  );
}
