// packages/svelte/reference-app/components/TaskItem.svelte
<script lang="ts">
  import { Link, useFetcher } from "remix-router-svelte";

  export let task;

  let fetcher = useFetcher();
  let isDeleting = fetcher.formData != null;
</script>

<span>{task.task}</span>
&nbsp;
<Link to="/tasks/{task.id}">Open</Link>
&nbsp;
<svelte:component
  this={fetcher.Form}
  style="display: inline"
  action="/tasks"
  method="post"
>
  <button type="submit" name="taskId" value={task.id} disabled={isDeleting}>
    {isDeleting ? "Deleting..." : "❌"}
  </button>
</svelte:component>

// packages/solid/referance-app/components/TaskItem.tsx
import { Link, useFetcher } from "remix-router-solid";

import type { Task } from "../tasks";

export interface TaskItemProps {
  task: Task;
}

export const TaskItem = ({ task }: TaskItemProps)  => {
  let fetcher = useFetcher();
  let isDeleting = () => {
      return fetcher().formData != null
    };
 const Form = fetcher().Form

  return (
    <>
      <span>{task.task}</span> <Link to={`/tasks/${task.id}`}>Open</Link>{" "}
      <Form style={{ display: "inline" }} action="/tasks" method="post">
        <button
          type="submit"
          name="taskId"
          value={task.id}
          disabled={isDeleting()}
        >
          {isDeleting() ? "Deleting..." : "❌"}
        </button>
      </Form>
    </>
  );
}
