// packages/svelte/src/components/Form/Form.svelte
<script lang="ts">
  import type { FormMethod } from "@remix-run/router";

  import {
    useFormAction,
    submitForm,
    getRouterContext,
    getRouteContext,
  } from "remix-router-svelte";

  export let replace: boolean = false;
  export let onSubmit: Function = undefined;
  export let fetcherKey: string = null;
  type HTMLFormSubmitter = HTMLButtonElement | HTMLInputElement;

  let { router } = getRouterContext();
  let routeId = getRouteContext().id;
  let defaultAction = useFormAction($$restProps.action as string);

  function submit(event: SubmitEvent) {
    onSubmit && onSubmit(event);
    if (event.defaultPrevented) {
      return;
    }
    event.preventDefault();
    submitForm(
      router,
      defaultAction,
      (event.submitter as HTMLFormSubmitter) || event.currentTarget,
      {
        method: $$restProps.method as FormMethod,
        replace,
      },
      fetcherKey,
      routeId
    );
  }
</script>

<form {...$$restProps} on:submit={submit}>
  <slot />
</form>

// packages/solid/src/components/Form.tsx
import { FormMethod } from "@remix-run/router";
import { JSX, mergeProps } from "solid-js";
import { useRouter } from "../context";
import { submitImpl, useFormAction } from "../hooks";

type HTMLFormSubmitter = HTMLButtonElement | HTMLInputElement;

export interface FormImplProps extends JSX.FormHTMLAttributes<HTMLFormElement> {
  replace: boolean;
  onSubmit ?: (e: SubmitEvent) => void;
  fetcherKey ?: string ;
  routeId ?: string ;
  children?: JSX.Element;
}

export const FormImpl = (props: FormImplProps) => {
  const router = useRouter();
  const defaultAction =  useFormAction(props.action);

  return (
    <form
      {...props}
      onSubmit={(e: SubmitEvent) => {
        props.onSubmit && props.onSubmit(e);
        if (e.defaultPrevented) {
          return;
        }
        e.preventDefault();
        submitImpl(
          router,
          defaultAction(),
          (e.submitter as HTMLFormSubmitter) || e.currentTarget,
          { method: props.method as FormMethod, replace: props.replace },
          props.fetcherKey,
          props.routeId
        );
      }}
    >
      {props.children}
    </form>
  );
};

export interface FormProps extends JSX.FormHTMLAttributes<HTMLFormElement>{
  replace?: boolean;
  onSubmit?: (e: SubmitEvent) => void;
}

export const Form = (props_ : FormProps) => {
    const props = mergeProps({replace : false}, props_);
    
    return <FormImpl  {...props}  />    
};
