// packages/react-stub/reference-app/App.tsx
import { createBrowserRouter, RouterProvider } from "react-router-dom";

import Boundary from "~/components/Boundary";
import Index from "~/routes/Index";
import Parent, { loader as parentLoader } from "~/routes/nested/Parent";
import Child, { loader as childLoader } from "~/routes/nested/Child";
import Redirect, { loader as redirectLoader } from "./routes/Redirect";
import ErrorComponent, { loader as errorLoader } from "./routes/Error";
import Root from "~/routes/Root";
import Tasks, {
  action as tasksAction,
  loader as tasksLoader,
} from "~/routes/tasks/Tasks";
import Task, { loader as taskLoader } from "~/routes/tasks/Task";
import NewTask, { action as newTaskAction } from "~/routes/tasks/NewTask";
import Defer, { loader as deferLoader } from "~/routes/Defer";

let routes = [
  {
    path: "/",
    element: <Root />,
    children: [
      {
        index: true,
        element: <Index />,
      },
      {
        path: "parent",
        loader: parentLoader,
        element: <Parent />,
        errorElement: <Boundary />,
        children: [
          {
            path: "child",
            loader: childLoader,
            element: <Child />,
          },
          {
            path: "error",
            loader: errorLoader,
            element: <ErrorComponent />,
          },
        ],
      },
      {
        path: "redirect",
        loader: redirectLoader,
        element: <Redirect />,
      },
      {
        path: "error",
        loader: errorLoader,
        element: <ErrorComponent />,
      },
      {
        path: "tasks",
        loader: tasksLoader,
        action: tasksAction,
        element: <Tasks />,
        children: [
          {
            path: ":id",
            loader: taskLoader,
            element: <Task />,
          },
          {
            path: "new",
            action: newTaskAction,
            element: <NewTask />,
          },
        ],
      },
      {
        path: "defer",
        loader: deferLoader,
        element: <Defer />,
      },
    ],
  },
];

let router = createBrowserRouter(routes);

export default function App() {
  return <RouterProvider router={router} fallbackElement={<p>Loading...</p>} />;
}

// packages/vue/reference-app/App.vue
<script setup lang="ts">
import {
  createBrowserRouter,
  RouterProvider,
  RouteObject,
} from "remix-router-vue";
import { h } from "vue";

import Boundary from "~/components/Boundary.vue";
import Root from "~/routes/Root.vue";
import Child, { loader as childLoader } from "~/routes/nested/Child.vue";
import Index from "~/routes/Index.vue";
import Parent, { loader as parentLoader } from "~/routes/nested/Parent.vue";
import Redirect, { loader as redirectLoader } from "~/routes/Redirect.vue";
import Error, { loader as errorLoader } from "~/routes/Error.vue";
import Tasks, {
  loader as tasksLoader,
  action as tasksAction,
} from "~/routes/tasks/Tasks.vue";
import Task, { loader as taskLoader } from "~/routes/tasks/Task.vue";
import NewTask, { action as newTaskAction } from "~/routes/tasks/NewTask.vue";
import Defer, { loader as deferLoader } from "~/routes/Defer.vue";

const routes: RouteObject[] = [
  {
    path: "/",
    element: Root,
    children: [
      {
        index: true,
        element: Index,
      },
      {
        path: "parent",
        loader: parentLoader,
        element: Parent,
        errorElement: Boundary,
        children: [
          {
            path: "child",
            loader: childLoader,
            element: Child,
          },
          {
            path: "error",
            loader: errorLoader,
            element: Error,
          },
        ],
      },
      {
        path: "redirect",
        loader: redirectLoader,
        element: Redirect,
      },
      {
        path: "error",
        loader: errorLoader,
        element: Error,
      },
      {
        path: "tasks",
        loader: tasksLoader,
        action: tasksAction,
        element: Tasks,
        children: [
          {
            path: ":id",
            loader: taskLoader,
            element: Task,
          },
          {
            path: "new",
            action: newTaskAction,
            element: NewTask,
          },
        ],
      },
      {
        path: "defer",
        loader: deferLoader,
        element: Defer,
      },
    ],
  },
];

const router = createBrowserRouter(routes);
const fallbackElement = () => h("p", "Loading...");
</script>

<template>
  <RouterProvider :router="router" :fallbackElement="fallbackElement" />
</template>
